import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(const MaterialApp(debugShowCheckedModeBanner:false, home: App()));

enum Status { scheduled, sent, cancelled }

class Contact {
  Contact({required this.id, required this.name, required this.phone, this.note='', this.fav=false});
  final String id; final String name; final String phone; final String note; final bool fav;
  Contact copy({String? id,String? name,String? phone,String? note,bool? fav}) => Contact(id:id??this.id,name:name??this.name,phone:phone??this.phone,note:note??this.note,fav:fav??this.fav);
  Map<String,dynamic> toJson()=>{'id':id,'name':name,'phone':phone,'note':note,'fav':fav};
  factory Contact.fromJson(Map<String,dynamic> j)=>Contact(id:j['id'],name:j['name']??'',phone:j['phone']??'',note:j['note']??'',fav:j['fav']??false);
}

class Job {
  Job({required this.id,this.contactId,required this.name,required this.phone,required this.text,required this.time,this.status=Status.scheduled});
  final String id; final String? contactId; final String name; final String phone; final String text; final DateTime time; final Status status;
  bool get due => !time.isAfter(DateTime.now());
  Job copy({String? id,String? contactId,String? name,String? phone,String? text,DateTime? time,Status? status})=>Job(id:id??this.id,contactId:contactId??this.contactId,name:name??this.name,phone:phone??this.phone,text:text??this.text,time:time??this.time,status:status??this.status);
  Map<String,dynamic> toJson()=>{'id':id,'contactId':contactId,'name':name,'phone':phone,'text':text,'time':time.toIso8601String(),'status':status.name};
  factory Job.fromJson(Map<String,dynamic> j)=>Job(id:j['id'],contactId:j['contactId'],name:j['name']??'',phone:j['phone']??'',text:j['text']??'',time:DateTime.tryParse(j['time']??'')??DateTime.now(),status:Status.values.firstWhere((s)=>s.name==j['status'],orElse:()=>Status.scheduled));
}

class App extends StatefulWidget { const App({super.key}); @override State<App> createState()=>_AppState(); }
class _AppState extends State<App>{
  final contacts=<Contact>[]; final jobs=<Job>[]; int tab=0; bool loaded=false;
  @override void initState(){super.initState(); load();}
  Future<void> load()async{final p=await SharedPreferences.getInstance(); contacts.addAll((p.getStringList('contacts')??[]).map((e)=>Contact.fromJson(jsonDecode(e)))); jobs.addAll((p.getStringList('jobs')??[]).map((e)=>Job.fromJson(jsonDecode(e)))); setState(()=>loaded=true);}
  Future<void> save()async{final p=await SharedPreferences.getInstance(); await p.setStringList('contacts',contacts.map((e)=>jsonEncode(e.toJson())).toList()); await p.setStringList('jobs',jobs.map((e)=>jsonEncode(e.toJson())).toList());}
  Future<void> openSms(String phone,String text)async{if(phone.trim().isEmpty)return; await launchUrl(Uri(scheme:'sms',path:phone,queryParameters:text.trim().isEmpty?null:{'body':text}),mode:LaunchMode.externalApplication);}
  Future<void> editContact([Contact? c])async{final r=await showModalBottomSheet<Contact>(context:context,isScrollControlled:true,builder:(_)=>ContactForm(c)); if(r==null)return; setState((){final i=contacts.indexWhere((x)=>x.id==r.id); if(i<0){contacts.add(r);}else{contacts[i]=r; for(var n=0;n<jobs.length;n++){if(jobs[n].contactId==r.id&&jobs[n].status==Status.scheduled){jobs[n]=jobs[n].copy(name:r.name,phone:r.phone);}}}}); save();}
  Future<void> editJob([Job? j, Contact? c])async{final r=await showModalBottomSheet<Job>(context:context,isScrollControlled:true,builder:(_)=>JobForm(contacts:contacts,job:j,contact:c)); if(r==null)return; setState((){final i=jobs.indexWhere((x)=>x.id==r.id); if(i<0)jobs.add(r); else jobs[i]=r;}); save();}
  @override Widget build(BuildContext context){if(!loaded)return const Scaffold(body:Center(child:CircularProgressIndicator())); return Scaffold(body:[SmsPage(contacts:contacts,onSms:openSms),ContactPage(contacts:contacts,onEdit:editContact,onDelete:(c){setState(()=>contacts.remove(c));save();},onSms:(c)=>openSms(c.phone,''),onSchedule:(c)=>editJob(null,c),onFav:(c){setState(){}}),SchedulePage(jobs:jobs,onEdit:editJob,onOpen:(j)=>openSms(j.phone,j.text),onSent:(j){setState(()=>jobs[jobs.indexOf(j)]=j.copy(status:Status.sent));save();},onCancel:(j){setState(()=>jobs[jobs.indexOf(j)]=j.copy(status:Status.cancelled));save();})][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.sms),label:'SMS'),NavigationDestination(icon:Icon(Icons.contacts),label:'Contacts'),NavigationDestination(icon:Icon(Icons.event_note),label:'Scheduler')]));}
}

class SmsPage extends StatefulWidget{const SmsPage({super.key,required this.contacts,required this.onSms});final List<Contact> contacts;final Future<void> Function(String,String) onSms;@override State<SmsPage> createState()=>_SmsPageState();}
class _SmsPageState extends State<SmsPage>{final phone=TextEditingController(), msg=TextEditingController();String id='';@override Widget build(BuildContext c){final selected=widget.contacts.where((x)=>x.id==id).firstOrNull;return Page(title:'SMS',children:[DropdownButtonFormField<String>(initialValue:id,items:[const DropdownMenuItem(value:'',child:Text('Manual number')),...widget.contacts.map((x)=>DropdownMenuItem(value:x.id,child:Text('${x.name} • ${x.phone}')))],onChanged:(v)=>setState((){id=v??''; if(selected!=null)phone.text=selected.phone;}),decoration:const InputDecoration(labelText:'Contact',border:OutlineInputBorder())),gap,TextField(controller:phone,enabled:id.isEmpty,decoration:const InputDecoration(labelText:'Phone',border:OutlineInputBorder())),gap,TextField(controller:msg,maxLines:5,decoration:const InputDecoration(labelText:'Message',border:OutlineInputBorder())),gap,FilledButton.icon(onPressed:()=>widget.onSms(selected?.phone??phone.text,msg.text),icon:const Icon(Icons.open_in_new),label:const Text('Open SMS'))]);}}

class ContactPage extends StatelessWidget{const ContactPage({super.key,required this.contacts,required this.onEdit,required this.onDelete,required this.onSms,required this.onSchedule,required this.onFav});final List<Contact> contacts;final Function(Contact?) onEdit;final Function(Contact) onDelete,onSms,onSchedule,onFav;@override Widget build(BuildContext c)=>Page(title:'Contacts',fab:()=>onEdit(null),children:[if(contacts.isEmpty)const Text('No contacts yet'),...contacts.map((x)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(x.name,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),IconButton(onPressed:()=>onFav(x),icon:Icon(x.fav?Icons.star:Icons.star_border))]),Text(x.phone),if(x.note.isNotEmpty)Text(x.note),Wrap(spacing:8,children:[FilledButton.tonalIcon(onPressed:()=>onSms(x),icon:const Icon(Icons.sms),label:const Text('Text now')),OutlinedButton.icon(onPressed:()=>onSchedule(x),icon:const Icon(Icons.event_note),label:const Text('Schedule')),OutlinedButton.icon(onPressed:()=>onEdit(x),icon:const Icon(Icons.edit),label:const Text('Edit')),OutlinedButton.icon(onPressed:()=>onDelete(x),icon:const Icon(Icons.delete),label:const Text('Delete'))])])))]);}

class SchedulePage extends StatelessWidget{const SchedulePage({super.key,required this.jobs,required this.onEdit,required this.onOpen,required this.onSent,required this.onCancel});final List<Job> jobs;final Function(Job?) onEdit;final Function(Job) onOpen,onSent,onCancel;@override Widget build(BuildContext c){final sorted=[...jobs]..sort((a,b)=>a.time.compareTo(b.time));return Page(title:'Scheduler',fab:()=>onEdit(null),children:[if(sorted.isEmpty)const Text('No scheduled texts'),...sorted.map((j)=>Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(j.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18))),Chip(label:Text(j.status.name))]),Text(j.phone),Text('${_d(j.time)} ${_t(j.time)} ${j.due?'• due':''}'),Text(j.text),Wrap(spacing:8,children:[FilledButton.tonalIcon(onPressed:j.status==Status.scheduled?()=>onOpen(j):null,icon:const Icon(Icons.sms),label:const Text('Open')),OutlinedButton(onPressed:()=>onEdit(j),child:const Text('Edit')),OutlinedButton(onPressed:j.status==Status.scheduled?()=>onSent(j):null,child:const Text('Sent')),OutlinedButton(onPressed:j.status==Status.scheduled?()=>onCancel(j):null,child:const Text('Cancel'))])])))]);}}

class ContactForm extends StatefulWidget{const ContactForm(this.c,{super.key});final Contact? c;@override State<ContactForm> createState()=>_ContactFormState();}
class _ContactFormState extends State<ContactForm>{late final name=TextEditingController(text:widget.c?.name??''),phone=TextEditingController(text:widget.c?.phone??''),note=TextEditingController(text:widget.c?.note??'');@override Widget build(BuildContext c)=>Sheet(children:[Text(widget.c==null?'Add contact':'Edit contact',style:head),gap,TextField(controller:name,decoration:const InputDecoration(labelText:'Name',border:OutlineInputBorder())),gap,TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone',border:OutlineInputBorder())),gap,TextField(controller:note,maxLines:3,decoration:const InputDecoration(labelText:'Note',border:OutlineInputBorder())),gap,FilledButton(onPressed:()=>Navigator.pop(context,Contact(id:widget.c?.id??DateTime.now().microsecondsSinceEpoch.toString(),name:name.text,phone:phone.text,note:note.text,fav:widget.c?.fav??false)),child:const Text('Save'))]);}

class JobForm extends StatefulWidget{const JobForm({super.key,required this.contacts,this.job,this.contact});final List<Contact> contacts;final Job? job;final Contact? contact;@override State<JobForm> createState()=>_JobFormState();}
class _JobFormState extends State<JobForm>{late String id=widget.job?.contactId??widget.contact?.id??'';late final phone=TextEditingController(text:widget.job?.contactId==null?widget.job?.phone??'':'');late final name=TextEditingController(text:widget.job?.contactId==null?widget.job?.name??'':'');late final msg=TextEditingController(text:widget.job?.text??'');late DateTime time=widget.job?.time??DateTime.now().add(const Duration(minutes:30));Contact? get contact=>widget.contacts.where((x)=>x.id==id).firstOrNull;@override Widget build(BuildContext c)=>Sheet(children:[Text(widget.job==null?'Schedule text':'Edit schedule',style:head),gap,DropdownButtonFormField<String>(initialValue:id,items:[const DropdownMenuItem(value:'',child:Text('Custom recipient')),...widget.contacts.map((x)=>DropdownMenuItem(value:x.id,child:Text('${x.name} • ${x.phone}')))],onChanged:(v)=>setState(()=>id=v??''),decoration:const InputDecoration(labelText:'Contact',border:OutlineInputBorder())),gap,if(id.isEmpty)...[TextField(controller:name,decoration:const InputDecoration(labelText:'Name',border:OutlineInputBorder())),gap,TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone',border:OutlineInputBorder())),gap],TextField(controller:msg,maxLines:4,decoration:const InputDecoration(labelText:'Message',border:OutlineInputBorder())),gap,Row(children:[Expanded(child:OutlinedButton(onPressed:pickDate,child:Text(_d(time)))),const SizedBox(width:8),Expanded(child:OutlinedButton(onPressed:pickTime,child:Text(_t(time))))]),gap,FilledButton(onPressed:save,child:const Text('Save'))]);Future<void> pickDate()async{final p=await showDatePicker(context:context,initialDate:time,firstDate:DateTime.now(),lastDate:DateTime.now().add(const Duration(days:730)));if(p!=null)setState(()=>time=DateTime(p.year,p.month,p.day,time.hour,time.minute));}Future<void> pickTime()async{final p=await showTimePicker(context:context,initialTime:TimeOfDay.fromDateTime(time));if(p!=null)setState(()=>time=DateTime(time.year,time.month,time.day,p.hour,p.minute));}void save(){final c=contact;Navigator.pop(context,Job(id:widget.job?.id??DateTime.now().microsecondsSinceEpoch.toString(),contactId:c?.id,name:c?.name??name.text,phone:c?.phone??phone.text,text:msg.text,time:time,status:Status.scheduled));}}

class Page extends StatelessWidget{const Page({super.key,required this.title,required this.children,this.fab});final String title;final List<Widget> children;final VoidCallback? fab;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),floatingActionButton:fab==null?null:FloatingActionButton(onPressed:fab,child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(18),children:children));}
class Sheet extends StatelessWidget{const Sheet({super.key,required this.children});final List<Widget> children;@override Widget build(BuildContext c)=>Padding(padding:EdgeInsets.fromLTRB(18,18,18,MediaQuery.of(c).viewInsets.bottom+18),child:ListView(shrinkWrap:true,children:children));}
const gap=SizedBox(height:12);const head=TextStyle(fontSize:24,fontWeight:FontWeight.bold);String _d(DateTime d)=>'${d.year}-${d.month.toString().padLeft(2,'0')}-${d.day.toString().padLeft(2,'0')}';String _t(DateTime d)=>'${d.hour.toString().padLeft(2,'0')}:${d.minute.toString().padLeft(2,'0')}';
